name: TrainCI

on:
  push:
    branches: [ master ]

jobs:
  phpunit:
    strategy:
      matrix:
        php_version: [8.2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: redis,xdebug
          coverage: xdebug
      - name: Install Dependencies
        run: composer install
      - name: PHPUnit Check
        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text
